# Generated by Django 2.2.10 on 2020-08-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='New Note', max_length=52)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Сервисная таблица',
                'verbose_name_plural': 'Сервисные записи',
            },
        ),
    ]
