# Generated by Django 2.2.10 on 2020-08-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200811_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255),
        ),
    ]
