# Generated by Django 2.2.10 on 2020-08-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200811_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='url',
        ),
        migrations.AlterField(
            model_name='pages',
            name='slug',
            field=models.CharField(max_length=255),
        ),
    ]
