# Generated by Django 2.2.10 on 2020-08-11 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200811_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Опционально, подпись к изображению', max_length=155, null=True)),
                ('image', models.ImageField(upload_to='img/%Y/%m/%d')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pages')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Опционально, подпись к файлу', max_length=155, null=True)),
                ('file', models.ImageField(upload_to='files/%Y/%m/%d')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pages')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, help_text='Опционально, когда для статьи необходимо выделить заголовок в отрыве от основной html разметки', max_length=155, null=True)),
                ('text', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pages')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
