# Generated by Django 2.2.10 on 2020-08-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200811_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='servicetable',
            options={'verbose_name': 'Сервисная таблица', 'verbose_name_plural': 'Сервисные записи'},
        ),
        migrations.RemoveField(
            model_name='pages',
            name='priority',
        ),
    ]
