# Generated by Django 2.2.10 on 2020-08-16 12:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200812_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='page',
        ),
        migrations.AlterField(
            model_name='articles',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Название альбома', max_length=255, null=True)),
                ('skin', models.ImageField(help_text='Обложка', upload_to='img/%Y/%m/%d')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pages')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.AddField(
            model_name='images',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Albums'),
        ),
    ]
