# Generated by Django 2.2.10 on 2020-08-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200816_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='show_in_slider',
            field=models.BooleanField(default=False),
        ),
    ]
