# Generated by Django 2.2.10 on 2020-08-21 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_images_show_in_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='текст, который вы видете в меню', max_length=50, verbose_name='название пункта меню')),
                ('priority', models.SmallIntegerField(default=1, help_text='чем ниже число, тем ближе к левому краю будет кнопка', verbose_name='приоритет')),
            ],
            options={
                'verbose_name': 'Пункт',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.AddField(
            model_name='pages',
            name='name_in_menu',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя кнопки в меню'),
        ),
        migrations.AlterField(
            model_name='images',
            name='show_in_slider',
            field=models.BooleanField(default=False, verbose_name='отображать в слайдере'),
        ),
        migrations.AddField(
            model_name='pages',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Выберите пункт меню, к которому прикреплена страница', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Topic', verbose_name='Пункт меню'),
        ),
    ]
