# Generated by Django 2.2.10 on 2020-08-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200821_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='priority',
            field=models.SmallIntegerField(default=10, help_text='чем ниже число, тем ближе к левому краю будет кнопка', verbose_name='приоритет'),
        ),
    ]
