# Generated by Django 2.2.10 on 2020-08-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200821_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL'),
        ),
    ]
